### ISSUE TITLE
[Backend] Create two new DDHQ mocks

### ISSUE THREAD

**Issue by akslaym** [BPR-Data-Team/Election-Night#130]

**Comment by isabelleashapiro** [comment]
Done: two tables for county and race ddhq mocks, two new lambda functions

In progress: adding identifier data to the json that is sent to clients to tell them where new data is coming from

**Comment by isabelleashapiro** [comment]
Note about the dynamo stream: I believe each time the data is updated in dynamo, each new row of data is sent as its own event. We should test what this looks like from the client's perspective because maybe there's a way to gather events in the trigger function and send large clumps of json data at once as opposed to individual rows separately?

**Comment by isabelleashapiro** [comment]
Done and edited responses to only include relevant data & table name
