### ISSUE TITLE
[BACKEND] Create Backend Proof of Concept

### ISSUE THREAD

**Issue by akslaym** [BPR-Data-Team/Election-Night#84]

**Comment by akslaym** [comment]
[] Create dynamo DB to receive this data from the lambda
[] Create lambda function to send fake data to a dynamo DB using batch write
[] Enable Dynamo DB Stream so that the new images get sent
[] Configure lambda that deals with new image sent by dynamo DB
[] Send this data to a mock web socket, which connects to a pie socket: https://piehost.com/websocket-tester
[] Check if we get new data when we update everything, one row, two row, and nothing (only time when we should not get new data)

**Comment by akslaym** [comment]
[ ] Create dynamo DB to receive this data from the lambda
[ ] Create lambda function to send fake data to a dynamo DB using batch write
[ ] Enable Dynamo DB Stream so that the new images get sent
[ ] Configure lambda that deals with new image sent by dynamo DB
[ ] Send this data to a mock web socket, which connects to a pie socket: https://piehost.com/websocket-tester
[ ] Check if we get new data when we update everything, one row, two row, and nothing (only time when we should not get new data)

**Comment by isabelleashapiro** [comment]
update 9/21:
- will try to come back to this later today or tmrw
- made lambda function that just prints events to cloudwatch when db is updated. this worked when manually inputting/taking out data, but realized cannot really test the "overwriting data with same data doesn't send stream" this way because deleting data sends a stream
- wrote basic lambda function to add data to mock dynamodb--it works as in it adds the data but I'm not seeing the stream result printed in cloudwatch when I run the function. going to look into this more and then adjust the test function to be batch write + add web socket stuff to the lambda stream trigger handler thing.

**Comment by isabelleashapiro** [comment]
ok came back and things seem to be working! haven't done websocket yet but batch-writing to dynamo sends something in the stream and when nothing changes (batch overwrite) nothing seems to come from the stream which is excellent.

**Comment by akslaym** [comment]
Completed!

**Comment by arielshif** [comment]
god this thread brings me so much joy
